import type { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/Footer/Footer";
import { Header } from "../components/Header/Header";
import { League } from "../hook/api/types";
import { useApi } from "../hook/api/useApi.hook";

interface HomeProps {
  leagues: League[];
}

const Home: NextPage<HomeProps> = ({ leagues }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header leagues={leagues} />
      <main></main>
      <Footer />
    </div>
  );
};

export async function getStaticProps() {
  const { getLeagues } = useApi();
  const leagues = await getLeagues();
  return {
    props: {
      leagues,
    },
  };
}

export default Home;
