import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/Header";
import { useApp } from "../context/useAppContext.hook";
import { Label, League } from "../hook/api/types";
import { useApi } from "../hook/api/useApi.hook";
import styles from "../styles/Home.module.css";

interface HomeProps {
  leagues: League[];
}

const Home: NextPage<HomeProps> = ({ leagues }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header leagues={leagues} />
      <main></main>
    </div>
  );
};

export async function getStaticProps() {
  const { getLeagues } = useApi();
  const leagues = await getLeagues();
  return {
    props: {
      leagues,
    },
  };
}

export default Home;
