import { NextPage } from "next";
import Head from "next/head";
import { useApp } from "../context/useAppContext.hook";
import { Signature } from "../hook/api/types";

const SignatureItem: React.FC<{ signature: Signature }> = ({ signature }) => {
  const { artist } = signature;
  return (
    <button className=" w-full btn">
      <div className="w-full flex flex-row items-center justify-between bg-primary rounded-xl p-2">
        <div className="avatar">
          <div className="w-24 rounded-xl">
            <img src={artist.image} />
          </div>
        </div>
        <div className="stat-value text-xl">{artist.name}</div>
        <div className="rating">
          <input type="radio" name="rating-2" className="mask mask-star-2 bg-orange-400" />
          <input type="radio" name="rating-2" className="mask mask-star-2 bg-orange-400" checked />
          <input type="radio" name="rating-2" className="mask mask-star-2 bg-orange-400" />
        </div>
      </div>
    </button>
  );
};

const Signature: NextPage = () => {
  const { currentSignatureAndArtist } = useApp();
  if (!currentSignatureAndArtist.length) return null;
  return (
    <div className="h-full w-full p-5 overflow-scroll">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-between h-full">
        {currentSignatureAndArtist.map(signature => {
          return (
            <div className="w-full my-3">
              <SignatureItem signature={signature} />
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default Signature;
