import { NextPage } from "next";
import Head from "next/head";

const Market: NextPage = () => {
  return (
    <div className="h-full w-full p-5 overflow-scroll">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-between h-full">Market</div>
    </div>
  );
};

export default Market;
